### ISSUE TITLE
Branch naming convention

### ISSUE THREAD

**Issue by ciherraiz** [devgranaja/probe#3]
If we will apply the git-flow (http://nvie.com/posts/a-successful-git-branching-model/) workflow, we need a naming convention for branches.

I suggest that convention:

- master
- develop
- feature/i[issue_number]/short_description
- hotfix/i[issue_number]/short_description

I guess, I can add a long description when I create a brach:

`git checkout -b [branch name]  "Branch for Adding More Graphs"`

Links:
http://www.guyroutledge.co.uk/blog/git-branch-naming-conventions/
https://stackoverflow.com/questions/273695/git-branch-naming-best-practices

**Comment by dmartosl** [comment]
So if I resolve an issue, I should create a new branch and merge into develop branch, is that so?

**Comment by ciherraiz** [comment]
Exactly! For example, I made a new branch for de issue #6. The new brach was named feature/i6/Config
